repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files


  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        #-   id: poetry-export
      - id: poetry-install

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'  # add version here
    hooks:
    - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.6'  # add version here
    hooks:
      - id: bandit
